### ISSUE TITLE
Make more stdlib support JS backend

### ISSUE THREAD

**Issue by ringabout** [ringabout/Nim#1]
- [x] xmltree
- [x] xmlparser
- [x] volatile
- [x] uri
- [x] unittest(nodejs)
- [ ] unicode
- [x] typetraits
- [x] times
- [ ] terminal
- [x] sugar
- [x] strutils
- [x] strtabs
- [x] strscans
- [x] strmisc
- [x] strformat
- [x] streamwrapper
- [x] streams
- [x] stats
- [x] ropes
- [ ] reservedmem
- [x] rationals
- [x] random
- [x] punycode
- [x] pegs
- [x] pathnorm
- [x] parsexml
- [x] parseutils
- [x] parsesql
- [x] parsejson
- [x] parsecsv
- [x] parsecfg
- [x] options
- [ ] oids
- [x] mimetypes
- [x] mersenne
- [ ] md5
- [x] math
- [ ] marshal
- [x] logging
- [x] lexbase
- [x] lenientops
- [x] json
- [x] httpcore
- [x] htmlparser
- [x] htmlgen
- [x] hashes
- [x] fenv
- [ ] endians
- [ ] encodings
- [x] cstrutils
- [x] cookies
- [x] complex
- [x] colors
- [x] bitops
- [x] base64
- [x] algorithm

**Comment by timotheecour** [comment]
* what about tracking things like `os`? that's a rather important one. Note that since ospaths is now merged into os, functionality from the old ospaths needs to work for js
* maybe add a separate list for nodejs (or in a separate issue preferably?)
* see `tests/js/tstdlib_imports.nim` which is the module that should be kept up to date to at least list the things that can be imported (a weaker but useful notion)
* i'd prefer a blacklist than a whitelist, ie: maintain a list of things that arent' yet supported on backend X (= js, nodejs, nimscript, etc), and check that all modules except that blacklist can be imported. see https://github.com/nim-lang/fusion/pull/24/files for an implementation of that that generates all modules recursively
blacklist is better because shorter (ideally!) and guarantees to stay in sync in case new modules are added; your tests will either fail (and blacklist should add that new module) or succeed (and that new module will be automatically tested)
